### ISSUE TITLE
Update packages to latest

### ISSUE THREAD

**Issue by bluepuma77** [bersling/svelte-capacitor-recipe#1]
Tried to get this up and running, but with those bleeding edge frameworks there are always a lot of changes:
```
Svelte      3 -> 4
SvelteKit   1 -> 2
Vite        4 -> 5
```
I updated packages with `ncu -u` ([link](https://www.npmjs.com/package/npm-check-updates)) and the whole project broke. 

Could you provide an updated "recipe"?

**Comment by bersling** [comment]
Thanks for reaching out. Which part of the recipe is outdated exactly? Does something break when following the recipe to create a new project or is the path for updating an already created project not clear?

Note: I didn't actually intend for people to clone the repo, rather to just follow the steps in the recipe. Maybe I should get rid of all the committed code except for the readme?

**Comment by bluepuma77** [comment]
I think the problem is the `vite` major update:
```
% npm run dev

> svelte-capacitor-recipe@0.0.1 dev
> vite dev

error when starting dev server:
file:///svelte-capacitor-recipe/svelte.config.js?ts=1709040730790:2
import { vitePreprocess } from '@sveltejs/kit/vite';
         ^^^^^^^^^^^^^^
SyntaxError: The requested module '@sveltejs/kit/vite' does not provide an export named 'vitePreprocess'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
```

I think it's great to have a running repo available. 

The things I still research is about how to enable functions like Push notifications and centrally register listeners.

**Comment by bersling** [comment]
Thanks for pointing out this problem. I've addressed it in the readme. However, I decided against the running repo. It's too much work to maintain that and it will always be outdated. It's way better to just have a working recipe and to actually follow that, that way people have the newest dependencies.
